++
Signed-off-by: Nikolay Mitrofanov <nikolay.mitrofanov@flant.com>

diff --git a/.github/ci_templates/e2e_tests.yml b/.github/ci_templates/e2e_tests.yml
--- a/.github/ci_templates/e2e_tests.yml
+++ b/.github/ci_templates/e2e_tests.yml
@@ -38,106 +38,6 @@
 # </template: set_e2e_requirement_status>
 {!{- end -}!}
 
-{!{ define "e2e_setup_step" }!}
-{!{- $ctx := . -}!}
-# <template: e2e_setup_step>
-- name: Setup
-  id: setup
-  env:
-    DECKHOUSE_REGISTRY_HOST: ${{secrets.DECKHOUSE_REGISTRY_HOST}}
-    CI_COMMIT_TAG: ${{needs.git_info.outputs.ci_commit_tag}}
-    CI_COMMIT_BRANCH: ${{needs.git_info.outputs.ci_commit_branch}}
-    CI_COMMIT_REF_SLUG: ${{needs.git_info.outputs.ci_commit_ref_slug}}
-    REF_FULL: ${{needs.git_info.outputs.ref_full}}
-    INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
-    MANUAL_RUN: {!{ coll.Has $ctx "manualRun" | conv.ToString | strings.Quote }!}
-  run: |
-    # Calculate unique prefix for e2e test.
-    # GITHUB_RUN_ID is a unique number for each workflow run.
-    # GITHUB_RUN_ATTEMPT is a unique number for each attempt of a particular workflow run in a repository.
-    # Add CRI and KUBERNETES_VERSION to create unique directory for each job.
-    # CRI and PROVIDER values are trimmed to reduce prefix length.
-    DHCTL_PREFIX=$(echo "${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}-$(echo ${CRI} | head -c 3)-${KUBERNETES_VERSION}")
-    if [[ "${MANUAL_RUN}" == "false" ]] ; then
-      # for jobs which run multiple providers concurrency (daily e2e, for example)
-      # add provider suffix to prevent "directory already exists" error
-      DHCTL_PREFIX="${DHCTL_PREFIX}-$(echo ${PROVIDER} | head -c 2)"
-    fi
-    # converts to DNS-like (all letters in lower case and replace all dots to dash)
-    # because it prefix will use for k8s resources names (nodes, for example)
-    DHCTL_PREFIX=$(echo "$DHCTL_PREFIX" | tr '.' '-' | tr '[:upper:]' '[:lower:]')
-
-    # Create tmppath for test script.
-    TMP_DIR_PATH=/mnt/cloud-layouts/layouts/${DHCTL_PREFIX}
-    if [[ -d "${TMP_DIR_PATH}" ]] ; then
-      echo "Temporary dir already exists: ${TMP_DIR_PATH}. ERROR!"
-      ls -la ${TMP_DIR_PATH}
-      exit 1
-    else
-      echo "Create temporary dir for job: ${TMP_DIR_PATH}."
-      mkdir -p "${TMP_DIR_PATH}"
-    fi
-
-    ## Source: ci_templates/build.yml
-
-    # Extract REPO_SUFFIX from repository name: trim prefix 'deckhouse/deckhouse-'.
-    REPO_SUFFIX=${GITHUB_REPOSITORY#deckhouse/deckhouse-}
-    if [[ $REPO_SUFFIX == $GITHUB_REPOSITORY ]] ; then
-      # REPO_SUFFIX should be empty for main repo 'deckhouse/deckhouse'.
-      REPO_SUFFIX=
-    fi
-
-    # Use dev-registry for Git branches.
-    BRANCH_REGISTRY_PATH="${DEV_REGISTRY_PATH}"
-    # Use rw-registry for Git tags.
-    SEMVER_REGISTRY_PATH="${DECKHOUSE_REGISTRY_HOST}/deckhouse"
-
-    if [[ -z ${DECKHOUSE_REGISTRY_HOST:-} ]] ; then
-      # DECKHOUSE_REGISTRY_HOST is empty, so this repo is not the main repo.
-      # Use dev-regisry for branches and Github Container Registry for semver tags.
-      BRANCH_REGISTRY_PATH="${DEV_REGISTRY_PATH}"
-      SEMVER_REGISTRY_PATH="${GHA_TEST_REGISTRY_PATH}"
-    fi
-
-    # Prepare initial image tag for deploy/deckhouse to test switching from previous release.
-    INITIAL_IMAGE_TAG=
-    if [[ -n ${INITIAL_REF_SLUG} ]] ; then
-      INITIAL_IMAGE_TAG=${INITIAL_REF_SLUG}${REPO_SUFFIX:+-${REPO_SUFFIX}}
-    fi
-
-    # Prepare image tag for deploy/deckhouse (DECKHOUSE_IMAGE_TAG option in testing/cloud_layouts/script.sh).
-    # CI_COMMIT_REF_SLUG is a 'prNUM' for dev branches or 'main' for default branch.
-    # Use it as image tag. Add suffix to not overlap with PRs in main repo.
-    IMAGE_TAG=${CI_COMMIT_REF_SLUG}${REPO_SUFFIX:+-${REPO_SUFFIX}}
-
-    INSTALL_IMAGE_NAME=
-    if [[ -n ${CI_COMMIT_BRANCH} ]]; then
-      # CI_COMMIT_REF_SLUG is a 'prNUM' for dev branches or 'main' for default branch.
-      INSTALL_IMAGE_NAME=${BRANCH_REGISTRY_PATH}/install:${IMAGE_TAG}
-    fi
-    if [[ -n ${CI_COMMIT_TAG} ]] ; then
-      REGISTRY_SUFFIX=$(echo ${WERF_ENV} | tr '[:upper:]' '[:lower:]') # CE/EE/FE -> ce/ee/fe
-      INSTALL_IMAGE_NAME=${SEMVER_REGISTRY_PATH}/${REGISTRY_SUFFIX}/install:${CI_COMMIT_REF_SLUG}
-    fi
-    SAFE_IMAGE_NAME=$(echo ${INSTALL_IMAGE_NAME} | tr '[:lower:]' '[:upper:]')
-    echo "Deckhouse Deployment will use install image ${SAFE_IMAGE_NAME} to test Git ref ${REF_FULL}"
-
-    # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
-    echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
-    docker pull "${INSTALL_IMAGE_NAME}"
-
-    echo '::echo::on'
-    echo "::set-output name=tmp-dir-path::${TMP_DIR_PATH}"
-    echo "::set-output name=dhctl-log-file::${TMP_DIR_PATH}/dhctl.log"
-    echo "::set-output name=dhctl-prefix::${DHCTL_PREFIX}"
-    echo "::set-output name=install-image-name::${INSTALL_IMAGE_NAME}"
-    echo "::set-output name=deckhouse-image-tag::${IMAGE_TAG}"
-    echo "::set-output name=initial-image-tag::${INITIAL_IMAGE_TAG}"
-
-    echo '::echo::off'
-
-# </template: e2e_setup_step>
-{!{- end -}!}
 
 {!{ define "e2e_send_alert_template" }!}
 {!{- $ctx := index . 0 -}!}
@@ -318,7 +218,7 @@ check_e2e_labels:
     ran_for: {!{ printf "%s;%s;%s;%s" $ctx.provider $ctx.layout $ctx.cri $ctx.kubernetesVersion | quote }!}
     failed_cluster_stayed: ${{ steps.check_stay_failed_cluster.outputs.failed_cluster_stayed }}
     issue_number: ${{ inputs.issue_number }}
-    ci_commit_ref_name: ${{ github.event.inputs.ci_commit_ref_name }}
+    install_image_path: ${{ github.event.inputs.install-image-path }}
     pull_request_ref: ${{ github.event.inputs.pull_request_ref }}
   env:
     PROVIDER: {!{ $ctx.providerName }!}
@@ -338,7 +238,103 @@ check_e2e_labels:
 {!{ tmpl.Exec "login_dev_registry_step" . | strings.Indent 4 }!}
 {!{ tmpl.Exec "login_rw_registry_step" . | strings.Indent 4 }!}
 {!{ tmpl.Exec "werf_install_step" . | strings.Indent 4 }!}
-{!{ tmpl.Exec "e2e_setup_step" . | strings.Indent 4 }!}
+
+    - name: Setup
+      id: setup
+      env:
+        DECKHOUSE_REGISTRY_HOST: ${{secrets.DECKHOUSE_REGISTRY_HOST}}
+        CI_COMMIT_TAG: ${{needs.git_info.outputs.ci_commit_tag}}
+        CI_COMMIT_BRANCH: ${{needs.git_info.outputs.ci_commit_branch}}
+        CI_COMMIT_REF_SLUG: ${{needs.git_info.outputs.ci_commit_ref_slug}}
+        REF_FULL: ${{needs.git_info.outputs.ref_full}}
+        INITIAL_REF_SLUG: ${{ github.event.inputs.initial_ref_slug }}
+        MANUAL_RUN: {!{ coll.Has $ctx "manualRun" | conv.ToString | strings.Quote }!}
+      run: |
+        # Calculate unique prefix for e2e test.
+        # GITHUB_RUN_ID is a unique number for each workflow run.
+        # GITHUB_RUN_ATTEMPT is a unique number for each attempt of a particular workflow run in a repository.
+        # Add CRI and KUBERNETES_VERSION to create unique directory for each job.
+        # CRI and PROVIDER values are trimmed to reduce prefix length.
+        DHCTL_PREFIX=$(echo "${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}-$(echo ${CRI} | head -c 3)-${KUBERNETES_VERSION}")
+        if [[ "${MANUAL_RUN}" == "false" ]] ; then
+          # for jobs which run multiple providers concurrency (daily e2e, for example)
+          # add provider suffix to prevent "directory already exists" error
+          DHCTL_PREFIX="${DHCTL_PREFIX}-$(echo ${PROVIDER} | head -c 2)"
+        fi
+        # converts to DNS-like (all letters in lower case and replace all dots to dash)
+        # because it prefix will use for k8s resources names (nodes, for example)
+        DHCTL_PREFIX=$(echo "$DHCTL_PREFIX" | tr '.' '-' | tr '[:upper:]' '[:lower:]')
+
+        # Create tmppath for test script.
+        TMP_DIR_PATH=/mnt/cloud-layouts/layouts/${DHCTL_PREFIX}
+        if [[ -d "${TMP_DIR_PATH}" ]] ; then
+          echo "Temporary dir already exists: ${TMP_DIR_PATH}. ERROR!"
+          ls -la ${TMP_DIR_PATH}
+          exit 1
+        else
+          echo "Create temporary dir for job: ${TMP_DIR_PATH}."
+          mkdir -p "${TMP_DIR_PATH}"
+        fi
+
+        ## Source: ci_templates/build.yml
+
+        # Extract REPO_SUFFIX from repository name: trim prefix 'deckhouse/deckhouse-'.
+        REPO_SUFFIX=${GITHUB_REPOSITORY#deckhouse/deckhouse-}
+        if [[ $REPO_SUFFIX == $GITHUB_REPOSITORY ]] ; then
+          # REPO_SUFFIX should be empty for main repo 'deckhouse/deckhouse'.
+          REPO_SUFFIX=
+        fi
+
+        # Use dev-registry for Git branches.
+        BRANCH_REGISTRY_PATH="${DEV_REGISTRY_PATH}"
+        # Use rw-registry for Git tags.
+        SEMVER_REGISTRY_PATH="${DECKHOUSE_REGISTRY_HOST}/deckhouse"
+
+        if [[ -z ${DECKHOUSE_REGISTRY_HOST:-} ]] ; then
+          # DECKHOUSE_REGISTRY_HOST is empty, so this repo is not the main repo.
+          # Use dev-regisry for branches and Github Container Registry for semver tags.
+          BRANCH_REGISTRY_PATH="${DEV_REGISTRY_PATH}"
+          SEMVER_REGISTRY_PATH="${GHA_TEST_REGISTRY_PATH}"
+        fi
+
+        # Prepare initial image tag for deploy/deckhouse to test switching from previous release.
+        INITIAL_IMAGE_TAG=
+        if [[ -n ${INITIAL_REF_SLUG} ]] ; then
+          INITIAL_IMAGE_TAG=${INITIAL_REF_SLUG}${REPO_SUFFIX:+-${REPO_SUFFIX}}
+        fi
+
+        # Prepare image tag for deploy/deckhouse (DECKHOUSE_IMAGE_TAG option in testing/cloud_layouts/script.sh).
+        # CI_COMMIT_REF_SLUG is a 'prNUM' for dev branches or 'main' for default branch.
+        # Use it as image tag. Add suffix to not overlap with PRs in main repo.
+        IMAGE_TAG=${CI_COMMIT_REF_SLUG}${REPO_SUFFIX:+-${REPO_SUFFIX}}
+
+        INSTALL_IMAGE_NAME=
+        if [[ -n ${CI_COMMIT_BRANCH} ]]; then
+          # CI_COMMIT_REF_SLUG is a 'prNUM' for dev branches or 'main' for default branch.
+          INSTALL_IMAGE_NAME=${BRANCH_REGISTRY_PATH}/install:${IMAGE_TAG}
+        fi
+        if [[ -n ${CI_COMMIT_TAG} ]] ; then
+          REGISTRY_SUFFIX=$(echo ${WERF_ENV} | tr '[:upper:]' '[:lower:]') # CE/EE/FE -> ce/ee/fe
+          INSTALL_IMAGE_NAME=${SEMVER_REGISTRY_PATH}/${REGISTRY_SUFFIX}/install:${CI_COMMIT_REF_SLUG}
+        fi
+        SAFE_IMAGE_NAME=$(echo ${INSTALL_IMAGE_NAME} | tr '[:lower:]' '[:upper:]')
+        echo "Deckhouse Deployment will use install image ${SAFE_IMAGE_NAME} to test Git ref ${REF_FULL}"
+
+        # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
+        echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
+        docker pull "${INSTALL_IMAGE_NAME}"
+
+        IMAGE_INSTALL_PATH="/${INSTALL_IMAGE_NAME#*/}"
+
+        echo '::echo::on'
+        echo "::set-output name=tmp-dir-path::${TMP_DIR_PATH}"
+        echo "::set-output name=dhctl-prefix::${DHCTL_PREFIX}"
+        echo "::set-output name=install-image-name::${INSTALL_IMAGE_NAME}"
+        echo "::set-output name=deckhouse-image-tag::${IMAGE_TAG}"
+        echo "::set-output name=initial-image-tag::${INITIAL_IMAGE_TAG}"
+        echo "::set-output name=install-image-path::${IMAGE_INSTALL_PATH}"
+
+        echo '::echo::off'
 
     - name: "Run e2e test: {!{ $ctx.providerName }!}/{!{ $ctx.criName }!}/{!{ $ctx.kubernetesVersion }!}"
       id: e2e_test_run
@@ -392,7 +388,6 @@ check_e2e_labels:
         PREFIX: ${{ steps.setup.outputs.dhctl-prefix}}
         INSTALL_IMAGE_NAME: ${{ steps.setup.outputs.install-image-name }}
         DECKHOUSE_IMAGE_TAG: ${{ steps.setup.outputs.deckhouse-image-tag }}
-        INITIAL_IMAGE_TAG: ${{ steps.setup.outputs.initial-image-tag }}
   {!{- tmpl.Exec "e2e_run_template" (slice .provider "cleanup") | strings.Indent 6 }!}
 
     - name: Save dhctl state
@@ -459,8 +454,6 @@ check_e2e_labels:
 {!{ $ctx.jobID }!}:
   name: "{!{ $ctx.jobName }!}"
   if: ${{ github.event.inputs.cri == '{!{ $ctx.cri }!}' && github.event.inputs.k8s_version == '{!{ $ctx.kubernetesVersion }!}' && github.event.inputs.layout == '{!{ $ctx.layout }!}' }}
-  needs:
-    - git_info
   env:
     PROVIDER: {!{ $ctx.providerName }!}
     CRI: {!{ $ctx.criName }!}
@@ -479,7 +472,44 @@ check_e2e_labels:
 {!{ tmpl.Exec "login_dev_registry_step" . | strings.Indent 4 }!}
 {!{ tmpl.Exec "login_rw_registry_step" . | strings.Indent 4 }!}
 {!{ tmpl.Exec "werf_install_step" . | strings.Indent 4 }!}
-{!{ tmpl.Exec "e2e_setup_step" . | strings.Indent 4 }!}
+
+    - name: Setup
+      id: setup
+      env:
+        DECKHOUSE_REGISTRY_HOST: ${{secrets.DECKHOUSE_REGISTRY_HOST}}
+        DHCTL_PREFIX: ${{ github.event.inputs.cluster_prefix }}
+        INSTALL_IMAGE_PATH: ${{ github.event.inputs.installer_image_path }}
+      run: |
+        # Create tmppath for test script.
+        TMP_DIR_PATH=/mnt/cloud-layouts/layouts/${DHCTL_PREFIX}
+        if [[ -d "${TMP_DIR_PATH}" ]] ; then
+          echo "Temporary dir already exists: ${TMP_DIR_PATH}. ERROR!"
+          ls -la ${TMP_DIR_PATH}
+          exit 1
+        else
+          echo "Create temporary dir for job: ${TMP_DIR_PATH}."
+          mkdir -p "${TMP_DIR_PATH}"
+        fi
+
+        INSTALL_IMAGE_NAME="${DECKHOUSE_REGISTRY_HOST:-}${INSTALL_IMAGE_PATH}"
+
+        SAFE_IMAGE_NAME=$(echo ${INSTALL_IMAGE_NAME} | tr '[:lower:]' '[:upper:]')
+        echo "Deckhouse Deployment will use install image ${SAFE_IMAGE_NAME} to test Git ref ${REF_FULL}"
+
+        # Print image name in uppercase to prevent hiding non-secret registry host stored in secret.
+        echo "⚓️ [$(date -u)] Pull 'dev/install' image '${SAFE_IMAGE_NAME}'."
+        docker pull "${INSTALL_IMAGE_NAME}"
+
+        arrPath=(${INSTALL_IMAGE_PATH//:/ })
+        DECKHOUSE_IMAGE_TAG="${arrPath[1]}"
+
+        echo '::echo::on'
+        echo "::set-output name=tmp-dir-path::${TMP_DIR_PATH}"
+        echo "::set-output name=install-image-full::${INSTALL_IMAGE_NAME}"
+        echo "::set-output name=deckhouse-image-tag::${DECKHOUSE_IMAGE_TAG}"
+        echo "::set-output name=initial-image-tag::${INITIAL_IMAGE_TAG}"
+
+        echo '::echo::off'
 
     - name: "Download state"
       id: download_artifact_with_state
@@ -502,9 +532,8 @@ check_e2e_labels:
         LAYOUT_SSH_KEY: ${{ secrets.LAYOUT_SSH_KEY}}
         TMP_DIR_PATH: ${{ steps.setup.outputs.tmp-dir-path}}
         PREFIX: ${{ github.event.inputs.cluster_prefix }}
-        INSTALL_IMAGE_NAME: ${{ steps.setup.outputs.install-image-name }}
+        INSTALL_IMAGE_NAME: ${{ steps.setup.outputs.install-image-full }}
         DECKHOUSE_IMAGE_TAG: ${{ steps.setup.outputs.deckhouse-image-tag }}
-        INITIAL_IMAGE_TAG: ${{ steps.setup.outputs.initial-image-tag }}
   {!{- tmpl.Exec "e2e_run_template" (slice .provider "cleanup") | strings.Indent 6 }!}
 
     - name: Remove failed cluster label
@@ -512,7 +541,7 @@ check_e2e_labels:
       uses: actions-ecosystem/action-remove-labels@v1
       with:
         github_token: ${{ secrets.BOATSWAIN_GITHUB_TOKEN }}
-        number: ${{ needs.git_info.outputs.pr_number }}
+        number: ${{ github.event.inputs.issue_number }}
         labels: "e2e/cluster/failed"
 
     - name: Cleanup temp directory
